import DS from 'ember-data';

export default DS.Model.extend({
  owner: DS.attr(),
  product_sku: DS.attr(),
  upc_code: DS.attr(),
  brand: DS.attr(),
  delivery_time: DS.attr(),
  product_attribute_set: DS.attr(),
  name: DS.attr(),
  description: DS.attr(),
  short_description: DS.attr(),
  qty: DS.attr(),
  weight: DS.attr(),
  width: DS.attr(),
  length: DS.attr(),
  height: DS.attr(),
  status: DS.attr(),
  approved: DS.attr(),
  categories: DS.attr(),
  websites: DS.attr(),
  tax_class: DS.attr(),
  url_key: DS.attr(),
  url_path: DS.attr(),
  magento_product_id: DS.attr(),
  price: DS.attr(),
  special_price: DS.attr(),
  special_cost: DS.attr(),
  special_from_date: DS.attr(),
  special_to_date: DS.attr(),
  is_special_price_approved: DS.attr(),
  image: DS.attr('file'),
  primaryImage: DS.attr('file'),
  images: DS.attr(),
  d_categories: DS.attr(),
  parentcategory: DS.attr(),
  subcategory: DS.attr()
});
